print ("I like food")
print ("I like travel")
print ("I like animals")
print ("I like reading")
print ("I like watching youtube")
print ("I like listening to music")
print ("I have a brother")
print ("I have no pets :(")